import { Employee, Task, DashboardStats } from "@/types/admin/Crm";

export const employees: Employee[] = [
  {
    id: "emp1",
    name: "Rahul Sharma",
    email: "rahul@dreambyte.in",
    phone: "+91 98765 43210",
    department: "Development",
    role: "Frontend Developer",
    joinDate: "2023-01-15",
  },
  {
    id: "emp2",
    name: "Priya Verma",
    email: "priya@dreambyte.in",
    phone: "+91 87654 32109",
    department: "Design",
    role: "UI/UX Designer",
    joinDate: "2022-11-01",
  },
  {
    id: "emp3",
    name: "Amit Rawat",
    email: "amit@dreambyte.in",
    phone: "+91 76543 21098",
    department: "Backend",
    role: "Node.js Developer",
    joinDate: "2023-03-20",
  },
  {
    id: "emp4",
    name: "Sneha Bisht",
    email: "sneha@dreambyte.in",
    phone: "+91 65432 10987",
    department: "QA",
    role: "QA Engineer",
    joinDate: "2023-06-10",
  },
];

export const tasks: Task[] = [
  {
    id: "task1",
    title: "Build Login Page",
    description: "Create responsive login page with validation",
    assignedTo: "emp1",
    frequency: "weekly",
    dueDate: "2025-06-20",
    status: "approved",
    deliveryStatus: "delivered",
    changes: [],
    createdAt: "2025-06-10",
  },
  {
    id: "task2",
    title: "Design Dashboard Mockup",
    description: "Prepare high-fidelity mockup for admin dashboard",
    assignedTo: "emp2",
    frequency: "monthly",
    dueDate: "2025-06-30",
    status: "pending",
    deliveryStatus: "not_delivered",
    changes: [
      {
        id: "ch1",
        changedAt: "2025-06-12",
        changedBy: "Admin",
        note: "Please add dark mode support to the mockup as well.",
      },
    ],
    createdAt: "2025-06-01",
  },
  {
    id: "task3",
    title: "Setup MongoDB Schema",
    description: "Define and implement database schema for CRM module",
    assignedTo: "emp3",
    frequency: "weekly",
    dueDate: "2025-06-18",
    status: "rejected",
    deliveryStatus: "delivered",
    changes: [
      {
        id: "ch2",
        changedAt: "2025-06-11",
        changedBy: "Admin",
        note: "Add indexing on email and createdAt fields.",
      },
    ],
    createdAt: "2025-06-08",
  },
  {
    id: "task4",
    title: "Write Test Cases",
    description: "Write unit and integration tests for auth module",
    assignedTo: "emp4",
    frequency: "monthly",
    dueDate: "2025-06-25",
    status: "pending",
    deliveryStatus: "not_delivered",
    changes: [],
    createdAt: "2025-06-05",
  },
  {
    id: "task5",
    title: "API Integration",
    description: "Integrate payment gateway APIs",
    assignedTo: "emp1",
    frequency: "monthly",
    dueDate: "2025-06-28",
    status: "pending",
    deliveryStatus: "not_delivered",
    changes: [],
    createdAt: "2025-06-07",
  },
];

export const getDashboardStats = (): DashboardStats => ({
  totalEmployees: employees.length,
  totalTasks: tasks.length,
  pendingTasks: tasks.filter((t) => t.status === "pending").length,
  approvedTasks: tasks.filter((t) => t.status === "approved").length,
  rejectedTasks: tasks.filter((t) => t.status === "rejected").length,
});