import { Brand, Employee, Task } from "@/types/superAdmin";

export const brands: Brand[] = [
  {
    id: "brand1",
    name: "AYM Yoga School",
    industry: "Health & Wellness",
    contactEmail: "info@aymyoga.com",
    contactPhone: "+91 98765 11111",
    website: "https://aymyoga.com",
    status: "active",
    createdAt: "2024-01-10",
  },
  {
    id: "brand2",
    name: "DreamByte Studio",
    industry: "Photography & Media",
    contactEmail: "hello@dreambyte.in",
    contactPhone: "+91 98765 22222",
    website: "https://dreambyte.in",
    status: "active",
    createdAt: "2024-03-05",
  },
  {
    id: "brand3",
    name: "Yakka Puka",
    industry: "Audit & Compliance",
    contactEmail: "contact@yakkapuka.com",
    contactPhone: "+91 98765 33333",
    status: "active",
    createdAt: "2024-05-20",
  },
  {
    id: "brand4",
    name: "RewardApp",
    industry: "Fintech",
    contactEmail: "support@rewardapp.in",
    contactPhone: "+91 98765 44444",
    status: "inactive",
    createdAt: "2024-07-01",
  },
];

export const employees: Employee[] = [
  {
    id: "emp1",
    employeeId: "DBS-2021-1995",
    name: "Rahul Sharma",
    email: "rahul@dreambyte.in",
    phone: "+91 98765 43210",
    dob: "1995-06-15",
    department: "Development",
    role: "admin",
    password: "Rahul@1234",
    joinDate: "2023-01-15",
    isActive: true,
  },
  {
    id: "emp2",
    employeeId: "DBS-2021-1998",
    name: "Priya Verma",
    email: "priya@dreambyte.in",
    phone: "+91 87654 32109",
    dob: "1998-03-22",
    department: "Design",
    role: "employee",
    password: "Priya@5678",
    joinDate: "2022-11-01",
    isActive: true,
  },
  {
    id: "emp3",
    employeeId: "DBS-2021-1997",
    name: "Amit Rawat",
    email: "amit@dreambyte.in",
    phone: "+91 76543 21098",
    dob: "1997-11-08",
    department: "Backend",
    role: "employee",
    password: "Amit@9012",
    joinDate: "2023-03-20",
    isActive: true,
  },
  {
    id: "emp4",
    employeeId: "DBS-2021-2000",
    name: "Sneha Bisht",
    email: "sneha@dreambyte.in",
    phone: "+91 65432 10987",
    dob: "2000-08-30",
    department: "QA",
    role: "employee",
    password: "Sneha@3456",
    joinDate: "2023-06-10",
    isActive: false,
  },
];

export const tasks: Task[] = [
  {
    id: "task1",
    title: "Build AYM Login Page",
    description: "Create responsive login page with OTP validation",
    assignedTo: "emp1",
    assignedBy: "super_admin",
    brandId: "brand1",
    frequency: "weekly",
    dueDate: "2025-06-20",
    status: "completed",
    deliveryStatus: "delivered",
    changes: [],
    createdAt: "2025-06-10",
  },
  {
    id: "task2",
    title: "Design DreamByte Mockups",
    description: "High-fidelity mockup for admin dashboard with dark mode",
    assignedTo: "emp2",
    assignedBy: "admin",
    brandId: "brand2",
    frequency: "monthly",
    dueDate: "2025-06-30",
    status: "pending",
    deliveryStatus: "not_delivered",
    changes: [
      {
        id: "ch1",
        changedAt: "2025-06-12",
        changedBy: "Admin",
        note: "Please add dark mode support to the mockup.",
      },
    ],
    createdAt: "2025-06-01",
  },
  {
    id: "task3",
    title: "Yakka Puka MongoDB Schema",
    description: "Define and implement database schema with indexing",
    assignedTo: "emp3",
    assignedBy: "admin",
    brandId: "brand3",
    frequency: "weekly",
    dueDate: "2025-06-18",
    status: "rejected",
    deliveryStatus: "delivered",
    rejectRemark: "Schema is missing proper indexing on email and createdAt fields. Please fix and resubmit.",
    changes: [],
    createdAt: "2025-06-08",
  },
  {
    id: "task4",
    title: "RewardApp Test Cases",
    description: "Write unit and integration tests for auth module",
    assignedTo: "emp4",
    assignedBy: "super_admin",
    brandId: "brand4",
    frequency: "monthly",
    dueDate: "2025-06-25",
    status: "pending",
    deliveryStatus: "not_delivered",
    changes: [],
    createdAt: "2025-06-05",
  },
  {
    id: "task5",
    title: "AYM Payment Integration",
    description: "Integrate Razorpay payment gateway",
    assignedTo: "emp1",
    assignedBy: "super_admin",
    brandId: "brand1",
    frequency: "one_time",
    dueDate: "2025-06-28",
    status: "pending",
    deliveryStatus: "not_delivered",
    changes: [],
    createdAt: "2025-06-07",
  },
];

export const getStats = (empList: Employee[], taskList: Task[], brandList: Brand[]) => ({
  totalEmployees: empList.length,
  totalTasksAllotted: taskList.length,
  totalTasksCompleted: taskList.filter((t) => t.status === "completed").length,
  totalTasksRejected: taskList.filter((t) => t.status === "rejected").length,
  totalTasksPending: taskList.filter((t) => t.status === "pending").length,
  totalBrands: brandList.length,
});